### ISSUE TITLE
[bug] PLATFORM=MAC(_ARM64) sets IOS CMake variable

### ISSUE THREAD

**Issue by mologie** [leetal/ios-cmake#101]
Hi! I find it awesome that ios-cmake supports macOS too now, it is very helpful for configuring Xcode properly, e.g. for symbol visibility which is often forgotten by one's casual CMake project.

**Describe the bug**

This toolchain always sets an "IOS" variable. Unfortunately, the "IOS" variable is used by projects such as OpenCV for determining whether they are on an iOS platform that provides iOS-specific libraries, e.g. UIKit. The "MACOS" platform provides no such headers.

**To Reproduce**

Build OpenCV with this toolchain, set PLATFORM=MAC.

**Expected behavior**

IOS should not be set because macOS is not iOS. However, if I were to build for MAC_CATALYST, I would expect that IOS was set.

**Environment**
* What version of CMake did you run? 3.19.6
* Your faulty CMakeLists.txt here: https://github.com/opencv/opencv/blob/master/modules/imgcodecs/CMakeLists.txt#L120

**Comment by leetal** [comment]
Hi! Awesome find! I'll correct this immediately on the dev branch! I'll get back to you here as soon as it's fixed!

**Comment by mologie** [comment]
Cool, thanks for the quick feedback, appreciate it :-). I have hackfixed the issue in the commit references above, but your YMMV: I have only confirmed that it fixes my macOS issue with CMake but have not tested beyond that, e.g. whether it breaks other stuff.

**Comment by leetal** [comment]
I have fixed this on the dev branch now (together with some other fixes as well regarding how dependencies are found/loaded) :)
