### ISSUE TITLE
How could I generate a fat library in arm64 armv7?

### ISSUE THREAD

**Issue by Yes-Jumby** [leetal/ios-cmake#109]
when i set PLATFORM_INT to OS,it will generate only arm64
I find the problem:
if(PLATFORM_INT STREQUAL "OS")
  set(SDK_NAME iphoneos)
  if(NOT ARCHS)
    set(ARCHS "armv7 arm64")//original set(ARCHS armv7 arm64)

**Comment by hhuwenjun** [comment]
I have the same problem. Have you solved it
