### ISSUE TITLE
CMake needs to run twice to configure project

### ISSUE THREAD

**Issue by oliverepper** [leetal/ios-cmake#110]
I made a small demo library [chuckle](https://github.com/oliverepper/chuckle) that serves as a demo on how to cross-compile some C++ code to macOS and iOS and use that resulting library in a Swift package. Everything works as expected, but only on the second run of the included build.sh script.
The first time you run cmake to configure this project no Makefile is generated, but on the second run it is. This might be related to using cpr and thus curl as a dependency in the project but since it only happens when using the toolchain I hope that someone here can point me in the right direction to fix this.

1. run the build.sh for the first time and you'll have no Makefile
2. run the very same command again and you'll have a working Makefile

**Expected behavior**
It should be successful on the first run.

**Environment**
* What version of CMake did you run?
I tried 3.20.5, and 3.20.2

* Your faulty CMakeLists.txt here:
Please check out the project [chuckle](https://github.com/oliverepper/chuckle). It's build for demo purpose.

P.S: It might be obvious but you don't need to run the complete build.sh to reproduce this. It's sufficient to run
```bash
cmake -S ./ -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DPLATFORM=OS64 \
            -DDEPLOYMENT_TARGET=14.0 \
            -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake \
            -DHAVE_SOCKET_LIBSOCKET=FALSE \
            -DHAVE_LIBSOCKET=FALSE \
            -B out/os64
```
this command 2 times.

**Comment by leetal** [comment]
Hmmm. Are you sure that this is not caused by FetchContent? All tests only run the cmake command once, and they work.

**Comment by leetal** [comment]
Is this still an issue? By design, CMake invokes the toolchain in every step, but my toolchain will only run once since all necessary arguments are set both in the cache as well as environment variables thus not needing multiple passes. But that said, CMake will still try to invoke the toolchain, which will just return() on subsequent runs.
