### ISSUE TITLE
Can it be used on ubuntu?

### ISSUE THREAD

**Issue by zuowanbushiwo** [leetal/ios-cmake#112]
Thank you very much for this open source project. Can I use this cmake configuration on ubuntu? Because I have not found a 
way to configure xcode and iossdk on ubuntu to use your ios.toolchain.cmake, can you give some guidance? Or is there a 
related project or docker?</br>
 Best regards,

**Comment by leetal** [comment]
Ubuntu is out of scope for this toolchain. It's (and only will) supporting macOS only. Dare i ask why you are trying to build an iOS app on a Linux machine?
