### ISSUE TITLE
[question] I want to compile FAT files containing armv7 and arm64, what should I do?

### ISSUE THREAD

**Issue by hhuwenjun** [leetal/ios-cmake#125]
I want to compile FAT files containing armv7 and arm64, what should I do?

**Comment by kambala-decapitator** [comment]
compile for desired platforms separately, then use `lipo` to merge binaries. Here's an example: https://github.com/kambala-decapitator/vcmi-ios-depends/blob/main/build_depends.sh#L233

**Comment by arsdever** [comment]
@kambala-decapitator I see recently (29 days ago) that you removed the `lipo` command execution from the file you are mentioning. Was there a specific reason for that or do you no longer need it?

My issue is that I'm trying to build for the `iOS + iOS Simulator` combined fat library, but the flag `OS64COMBINED` doesn't seem to work.

**Comment by kambala-decapitator** [comment]
@arsdever I don't merge device and simulator builds because both contain arm64 slice.

but the simulator libs merge is still there, see https://github.com/kambala-decapitator/vcmi-ios-depends/blob/main/deps/nullkiller/tbb.sh#L71
