### ISSUE TITLE
Question: set_xcode_property

### ISSUE THREAD

**Issue by hsdk123** [leetal/ios-cmake#128]
Hi, I see we have the function `set_xcode_property` - how do we know the names of the attributes we can configure?

**Comment by leetal** [comment]
Apple has an extensive list available at [Apple's Xcode help reference](https://help.apple.com/xcode). You just have to search for "build settings" and select the first entry that pops up in the list. :) Finding the correct variable can be cumbersome sometimes and sadly there is no better way other than searching in that webpage for keywords you're interested in.
