### ISSUE TITLE
[question] How to generate ipa file with this toolchain ?

### ISSUE THREAD

**Issue by EndrII** [leetal/ios-cmake#132]
i build my Qt application using static build. After build i get folder APP_NAME.app with my static application and them sign.

i tried to compress the release folder to zip archive and rename zip file to ipa file. But after upload a have a error 
message "invalid ipa package"

error message:
```
ERROR ITMS-90072: "The IPA is invalid. It does not include a Payload directory."
```

Please add detail instruction for build ipa packages for upload to app store.

Thank you.

**Comment by kambala-decapitator** [comment]
packaging ipa has nothing to do with this toolchain.

you must put the built .app in `Payload` directory, then zip the `Payload` directory.

**Comment by leetal** [comment]
Closing this due to the above mentioned comment. This is outside the scope of this CMake toolchain.
