### ISSUE TITLE
Trying to use `ios-cmake` toolchain but I get an empty project

### ISSUE THREAD

**Issue by oskargargas** [leetal/ios-cmake#135]
Hi,

I try to incorporate `ios-cmake` into our build setup but I consistently get empty Xcode project.

My goal is to build RapidFuzz C++ library as a dynamic framework for iOS and Simulator
https://github.com/maxbachmann/rapidfuzz-cpp/tree/b2240f75cb0308cdf928ead4e1f6422a7a3c4efa

I use following command:
```sh
mkdir build
cd build
cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../../ios-cmake/ios.toolchain.cmake -DPLATFORM=OS64COMBINED -DDEPLOYMENT_TARGET=13.0
```

Is it problem on my side? Is it problem with CMakeList? Can I do something without modifying external CMakeList?

**Comment by leetal** [comment]
I'll look into this as soon as i've figured out the fixes needed to get XCode 13.3+ and CMake 3.23+ to work with this toolchain!
