### ISSUE TITLE
error while compile libevent with -DPLATFORM=OS64COMBINED

### ISSUE THREAD

**Issue by manang** [leetal/ios-cmake#136]
Hi, I'm trying to compile libevent for iOS with DPLATFORM=OS64COMBINED parameter passed to cmake.
The output of "cmake build" is: 
note: Build preparation complete
note: Building targets in dependency order
error: unable to attach DB: error: accessing build database "build/libevent/build/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.

do you know if there is a solution for this?
Thanks

**Comment by manang** [comment]
it is not only libevent, but every library that I compile with cmake. does OS64COMBINED work?
Thanks

**Comment by manang** [comment]
solved, wrong cmake parameters

**Comment by emctague** [comment]
@manang might I ask what CMake parameters you changed to fix the database locking issue? I am dealing with the exact same issue, CMake absolutely refuses to produce a fat lib using this setting

**Comment by manang** [comment]
this is my command
`cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../ios.toolchain.cmake -DPLATFORM=OS64 -DCMAKE_FIND_ROOT_PATH=../../usr -DCMAKE_INSTALL_PREFIX=../..//usr/ -DOPENSSL_ROOT_DIR=../../usr -DEVENT__DISABLE_TESTS=ON -DEVENT__DISABLE_SAMPLES=ON -DEVENT__LIBRARY_TYPE=STATIC -DEVENT__HAVE_EPOLL=OFF -DEVENT__HAVE_PIPE2=OFF -DEVENT__DISABLE_BENCHMARK=ON  -DEVENT__DISABLE_MBEDTLS=ON && OBJROOT="${OBJROOT}/DependantBuilds" && cmake --build . --config Release && cmake --install . --config Release
`

the build and install fase have to be separated.
that was my error
let me know
