### ISSUE TITLE
[PROPOSAL] Explicit support of CMake OBJC/OBJCXX languages

### ISSUE THREAD

**Issue by ceztko** [leetal/ios-cmake#139]
Starting with version 3.16[1], CMake learned explicit support for ObjC and ObjC++ languages. This means that the projects can be enabled with `project()` or `enable_language()` directives (example `project(MyProject OBJCXX)` ) to better control the behavior of CMake when dealing with `.m` or `.mm` files, enabling specifying the set of `CMAKE_OBJC_FLAGS` like variables. Sometimes this may be also the solution to fix some nasty bugs that require different sets of flags for `.c`/.`cpp` and `.m`/`.mm` files respectively. Attached is a patch to the current version of `ios.toolchain.cmake` (easily apply to latest [14092d3](https://github.com/leetal/ios-cmake/commit/14092d317b84a3037e71b870d2117dda126811a3) revision), which I'm personally using in my project. It basically adds all the required variables `CMAKE_{OBJC|OBJCXX}_FLAGS` and `CMAKE_{OBJC|OBJCXX}_FLAGS_<config>`. All the ObjC specific flags from `CMAKE_{C|CXX}_FLAGS_<config>` are moved to `CMAKE_{OBJC|OBJCXX}_FLAGS_<config>`, plus others taken directly from XCode project defaults which are working well for me. The patch also introduces some unrelated cleanings/improvements that I highly recommend including as well. They are:

- Removed the expansion of `CMAKE_<lang>_FLAGS` in `CMAKE_<lang>_FLAGS_<config>` variables: this is unnecessary and may create unpredictable behavior when the user want to customize the flags separately. CMake correctly creates the set of flags for the compilation units anyway without this forced early expansion;
- Addded the missing `CMAKE_C_FLAGS_<config>` flags. There's no reason why they should not be specified as well;
- Add the `${VISIBILITY}` flags to all languages: as it is there's no reason why it should be only in C++;
- Removed the `-ffast-math` flag from `CMAKE_<lang>_FLAGS_RELEASE`: this may be undesirable for some users and it's not part of flags CMake uses in unix plaftorms for `Release` builds by default.

These modifications come as a patch and not as a pull request because they assume the user will manually enable `OBJC` and/or `OBJCXX` languages in their projects, so in the current state it's a breaking change. I suggest creating a legacy mode that works as before, plus a new mode that assumes explicit `OBJC`, `OBJCXX` support enabled, that has the new set of flags as suggested in the patch set.

[OBJC_OBJCXX_support.diff.txt](https://github.com/leetal/ios-cmake/files/8395804/OBJC_OBJCXX_support.diff.txt)

[1] https://cmake.org/cmake/help/latest/release/3.16.html

**Comment by ceztko** [comment]
Of course this is not a bug but I could not change the label.

**Comment by leetal** [comment]
Hi! Thanks for supplying this patch! I'll look into this as it will probably solve #138 as well :)

**Comment by glebm** [comment]
This patch does indeed fix #138 https://github.com/diasurgical/devilutionX/runs/5816366433?check_suite_focus=true

**Comment by ceztko** [comment]
> Hi! Thanks for supplying this patch! I'll look into this as it will probably solve https://github.com/leetal/ios-cmake/issues/138 as well :)

You're welcome! also, elaborating more about my recommended improvements, I thought a little bit about this one:
> Add the ${VISIBILITY} flags to all languages: as it is there's no reason why it should be only in C++;

If OjbC/OjbC++ languages are explicitly enabled, maybe it's better to not enforce any "guided" behavior for C/C++ compilation units. That said, maybe for the latter languages it would be better to **not** append `${VISIBILITY}` flags, like the following:

```
  set(CMAKE_C_FLAGS "${C_TARGET_FLAGS} ${APPLE_TARGET_TRIPLE_FLAG} ${SDK_NAME_VERSION_FLAGS} ${BITCODE} ${CMAKE_C_FLAGS}")
  set(CMAKE_CXX_FLAGS "${C_TARGET_FLAGS} ${APPLE_TARGET_TRIPLE_FLAG} ${SDK_NAME_VERSION_FLAGS} ${BITCODE} ${CMAKE_CXX_FLAGS}")"
```

Also, I probably forgot appending `${C_TARGET_FLAGS} ${APPLE_TARGET_TRIPLE_FLAG}` to `CMAKE_OBJC_FLAGS` and `CMAKE_OBJCXX_FLAGS`.

**Comment by ceztko** [comment]
Hello, I just wanted to say thank you for integrating my patch basically with all the suggestions I mentioned: I just upgraded `ios.toolchain.cmake` and I was finally able to use it with no modifications, so I'm very happy!
