### ISSUE TITLE
Preventing the toolchain to run as an environment variable breaks further runs.

### ISSUE THREAD

**Issue by JonasVautherin** [leetal/ios-cmake#146]
[This](https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake#L147-L150) breaks my build:

```cmake
if(DEFINED ENV{_IOS_TOOLCHAIN_HAS_RUN})
  return()
endif()
set(ENV{_IOS_TOOLCHAIN_HAS_RUN} true)
```

Where the previous version is fine:

```cmake
if(IOS_TOOLCHAIN_HAS_RUN)
  return()
endif(IOS_TOOLCHAIN_HAS_RUN)
set(IOS_TOOLCHAIN_HAS_RUN true)
```

I believe that's because it now sets this as an environment variable, and the second time I try to build  a project using the toolchain, it just doesn't do anything.

Feels weird to me that I need to `unset _IOS_TOOLCHAIN_HAS_RUN` between two cmake runs, though :thinking:.

Any thoughts on that? :innocent:

**Comment by leetal** [comment]
Hmmm, i have never had to unset the environment variables between runs? I cannot remember either why i changed that in the first place... Seems to run equally good using both the "old" solution as with the ENV solution.

**Comment by JonasVautherin** [comment]
Does it work if you do something like this?

```
export _IOS_TOOLCHAIN_HAS_RUN=true
cmake -DCMAKE_TOOLCHAIN_FILE=<...> -B<...> -S<...>
cmake --build <...>
```

It will disable the toolchain, right?

Similarly, without manually setting the env variable, if you run it twice:

```
cmake -DCMAKE_TOOLCHAIN_FILE=<...> -BprojectA/build -SprojectA
cmake --build projectA
cmake -DCMAKE_TOOLCHAIN_FILE=<...> -BprojectB/build -SprojectB
cmake --build projectB
```

Then I expect the first run to set the env variable (just like `export` above), and disable the toolchain for further projects, right?

I have a slightly different setup where my cmake project calls cmake projects as subprocesses, but I think it's similar :thinking:.

**Comment by depnz** [comment]
An interesting, related issue is if a CMake project includes a subproject, where the subproject will set and use the toolchain. When the top level project then tries to use the same tool chain, it does not configure fully.

This leads to the situation where e.g. `DEPLOYMENT_TARGET` settings for the subproject are respected, but all these sorts of settings are defaulted-out for the top-level project, as if the toolchain was not even set.

I'm employing the workaround `unset(ENV{_IOS_TOOLCHAIN_HAS_RUN})` as a final step when the subproject is included.

**Comment by JonasVautherin** [comment]
It is still [here](https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake#L154-L157), and given [this past message](https://github.com/leetal/ios-cmake/issues/146#issuecomment-1132930553):

> I cannot remember either why i changed that in the first place... Seems to run equally good using both the "old" solution as with the ENV solution.

@leetal: would you be open to a PR that would either remove those lines or add an option (e.g. `ALWAYS_RUN`) to work around it?
