### ISSUE TITLE
[bug] Incorrect information in the README file

### ISSUE THREAD

**Issue by arsdever** [leetal/ios-cmake#156]
**Describe the bug**
The [README](https://github.com/leetal/ios-cmake/blame/master/README.md#L34) file states the `OS64COMBINED` flag builds a fat lib including `iphoneOS` and `iphoneOS Simulator`, but in the [toolchain file](https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake#L61) the statement is completely different.

**To Reproduce**

**Expected behavior**
The documentation is correct

**Environment**

```cmake
#    OS64COMBINED = Build for arm64 x86_64 iphoneOS. Combined into FAT STATIC lib (supported on 3.14+ of CMakewith "-G Xcode" argument ONLY)
```

**Comment by leetal** [comment]
This has now been clarified the the ios.toolchain.cmake file as well as that the `cmake --install ` step is necessary. Please respond is OK, and then I'll close this issue.

**Comment by arsdever** [comment]
@leetal my main concern is that on the main page, master branch, the information is still incorrect in the `README.md`. I read there, that the fat lib can be generated via specifying `OS64COMBINED`, which is not correct.
<img width="588" alt="Screen Shot 2022-08-24 at 14 09 32" src="https://user-images.githubusercontent.com/22396275/186392626-8d3ad044-96fb-48f5-ba39-0010b06383ff.png">
