### ISSUE TITLE
Feature: Add Support for Universal macOS builds (Apple Silicon + Intel)

### ISSUE THREAD

**Issue by DctrNoob** [leetal/ios-cmake#162]
I am currently missing an option to build fat executables on macOS that contain both Apple Silicon and Intel executables. I'll create a PR that does just that: introducing a new platform option "MAC_UNIVERSAL" that by default configures the architectures x86_64 and arm64.

**Comment by DctrNoob** [comment]
See https://github.com/leetal/ios-cmake/pull/163.

**Comment by leetal** [comment]
#163 is now merged. Closing!
