### ISSUE TITLE
[question] Issue with APPLE_TARGET_TRIPLE (aarch64-apple-ios/arm64-apple-ios)

### ISSUE THREAD

**Issue by Nekto89** [leetal/ios-cmake#165]
I'm new to cross-compiling so I may be doing something wrong. I've tried using this toolchain together with cmake-conan script. I'm having problem with auto-detecting of compiler here: https://github.com/conan-io/cmake-conan/blob/835529148ac0def63bbd1d07ceb4e4c130d233af/conan.cmake#L370
In my case:
`cmake -E echo "#include <string>" | /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ --target=aarch64-apple-ios11.0 -fvisibility=hidden -fvisibility-inlines-hidden -x c++ --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk  -E -dM -`
This leads to `error: unknown target triple 'unknown-apple-ios11.0.0', please use -triple or -arch`

I've tried googling and found this issue https://groups.google.com/g/llvm-dev/c/PIBNR1EE9R0
Running the same command with `arm64-apple-ios11.0` instead of `aarch64-apple-ios11.0` seems to be working.
`cmake -E echo "#include <string>" | /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ --target=arm64-apple-ios11.0 -fvisibility=hidden -fvisibility-inlines-hidden -x c++ --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk  -E -dM -`

So should something be changed in cmake-conan or in this toolchain (maybe CMAKE_CXX_COMPILER_TARGET should be different in this case)?

-- Using Xcode version: 12.0.1
-- CMake version: 3.23.1

**Comment by kambala-decapitator** [comment]
cmake-conan is a legacy thing. I'd strongly recommend you to adopt the new way of using build+host profiles where building for iOS works out of the box without the need of this toolchain.

**Comment by Nekto89** [comment]
> cmake-conan is a legacy thing. I'd strongly recommend you to adopt the new way of using build+host profiles where building for iOS works out of the box without the need of this toolchain.

I couldn't find a way to adopt new experimental way yet - I need to be able to call conan multiple times from different places that require different thirdparty libraries. So I can't have single conanfile.txt. And full list of libraries highly depends on cmake options. Also some options for thirdparties are dynamically switched in CMake before call to conan. But this is offtopic for this issue.

**Comment by Nekto89** [comment]
> you can have single conanfile.py with various options that would define your cmake options, then you'd invoke cmake with proper options right from the conanfile.py. Check https://docs.conan.io/en/latest/reference/conanfile/tools/cmake.html#conan-tools-cmake
> 
> FYI the new "experimental" way would be the only way in Conan v2 as well as the new cmake integration I linked. I'd say it makes sense to invest time into it :)
> 
> you can also ask on Conan slack for migration hints from your current approach to the recommended one.

I need package manager just to download thirdparties. conanfile.py isn't convenient for developing code - it's main purpose is just to build and package binaries. I'm not going to rewrite hundreds of linked projects just to make conan happy. If there would be no workarounds - I'll probably stay with old version until I can switch to some other package manager (for example, vcpkg).

**Comment by leetal** [comment]
I just followed the "standard" when setting aarch64 instead om arm64 in the triples. But yes, I've verified the outcome in llvm and it seems that when set in "Apple mode", the compiler indeed require arm64 as the triple-architecture... Not sure what do do about this since the toolchain currently obeys the standards, but is on the other hand also targeting Apple platforms.. 🤦
