### ISSUE TITLE
how to omit -G Xcode to use Makefile or use -G Ninjau

### ISSUE THREAD

**Issue by lixue106361** [leetal/ios-cmake#167]
**Describe the bug**
I want to use -G Ninja instead of -G Xcode or omit -G Xcode, it prodece bug.

CMake Error at /Users/lixue32/ios_cmake_example/ios-cmake/ios.toolchain.cmake:212 (message):
  The combined builds support requires Xcode to be used as a generator via
  '-G Xcode' command-line argument in CMake
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/CMakeDetermineSystem.cmake:90 (include)
  CMakeLists.txt:2 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

**To Reproduce**
1. cmake . -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DPLATFORM=OS64COMBINED
2. cmake . -G Ninja -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DPLATFORM=OS64COMBINED

**Expected behavior**
how to fix this bug

**Environment**
* What version of CMake did you run?
3.18.4

**Comment by kambala-decapitator** [comment]
like the message says, you can make "combined" builds with Xcode.

to use non-Xcode generator, make non-combined builds, then `lipo` the built libraries together.

**Comment by leetal** [comment]
This is correct. A "limitation" (design choice) in CMake. Closing this issue.
