### ISSUE TITLE
Compiler detection issue

### ISSUE THREAD

**Issue by IlyaBizyaev** [leetal/ios-cmake#18]
Hello!

When building QXmpp and my Qt application with ios-cmake, I get this error:
```
CMake Error in src/CMakeLists.txt:
No known features for CXX compiler
"AppleClang"
version 10.0.0.10001145. 
```
How can I troubleshoot?

**Comment by leetal** [comment]
Hi, this seems to be a QT feature check.

See https://stackoverflow.com/questions/38027292/configure-a-qt5-5-7-application-for-android-with-cmake/40256862#40256862 <https://stackoverflow.com/questions/38027292/configure-a-qt5-5-7-application-for-android-with-cmake/40256862#40256862> for a possible workaround.

**Comment by IlyaBizyaev** [comment]
Thank you @leetal, that indeed solved the issue!
