### ISSUE TITLE
command not found: cmake

### ISSUE THREAD

**Issue by ZFbaby** [leetal/ios-cmake#185]
**Describe the bug**

**To Reproduce**
1. 
2.

**Expected behavior**

**Environment**
* What version of CMake did you run?
* Your faulty CMakeLists.txt here:
```cmake
--- Paste here ---
```
 build % cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DPLATFORM=OS64
cmake --build . --config Release
zsh: command not found: cmake

**Comment by leetal** [comment]
This is outside the scope of this toolchain. Closing.
