### ISSUE TITLE
ARM64 support for WATCHOS simulator is missing.

### ISSUE THREAD

**Issue by YudrB** [leetal/ios-cmake#188]
None of the platform options for WATCHOS produce an ARM64 build which is needed for the simulator running on Apple Silicon.
For example when attempting to build on an M2 MacBook.

My Environment is:
- MacBookAir M2
- Latest version of CMAKE
- current main branch 

I have a local fix for this, but new to open source and not exactly sure how to contribute it.

**Comment by kambala-decapitator** [comment]
> I have a local fix for this, but new to open source and not exactly sure how to contribute it.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by leetal** [comment]
Fixed in #189
