### ISSUE TITLE
Wrong minimum OS version flags when IOS_PLATFORM is set to OS64

### ISSUE THREAD

**Issue by Antonz0** [leetal/ios-cmake#19]
It looks that in latest version when IOS_PLATFORM is set to "OS64" a toolchain scripts sets wrong flags for minimum required OS version: it sets "-mios-simulator-version-min" instead of "-mios-version-min" because corresponding if/elseif block that checks for value of IOS_PLATFORM  is missing check for "OS64" value (it must treat it the same as "OS", I think).

Current workaround is to use "-DIOS_PLATFORM=OS" and manually select architectures with "-DIOS_ARCH=<your archs>" if they need to be customized.

**Comment by leetal** [comment]
Hi! Thanks for finding this. I'll get right on it and a new release will be created as well.
