### ISSUE TITLE
[bug] CMAKE_OSX_DEPLOYMENT_TARGET not CACHE

### ISSUE THREAD

**Issue by st751228051** [leetal/ios-cmake#191]
**Describe the bug**
ios-cmake-4.4.1, build with "-DPLATFORM=MAC -DARCHS=x86_64", top display 10.13, but actualy -target x86_64-apple-macos13.3.

**To Reproduce**
1. ios-cmake-4.4.1
2. build with "-DPLATFORM=MAC -DARCHS=x86_64"
3. top display "-- Autoconf target triple: x86_64-apple-macosx10.13
-- Using minimum deployment version: 10.13 (SDK version: 13.3)",
 but bottom actualy "-target x86_64-apple-macos13.3".

**Expected behavior**
-target x86_64-apple-macos10.13

**Environment**
* What version of CMake did you run? 3.27.7
* Your faulty CMakeLists.txt here: no
```cmake
--- Paste here ---
```

Clue:
https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html#variable:CMAKE_OSX_DEPLOYMENT_TARGET
This variable should be set as a CACHE entry (or else CMake may remove it while initializing a cache entry of the same name) unless policy [CMP0126](https://cmake.org/cmake/help/latest/policy/CMP0126.html#policy:CMP0126) is set to NEW.

I change ios.toolchain.cmake Line:829 "set(CMAKE_OSX_DEPLOYMENT_TARGET ${DEPLOYMENT_TARGET})" to "set(CMAKE_OSX_DEPLOYMENT_TARGET ${DEPLOYMENT_TARGET} CACHE STRING "Minimum OS X deployment version")",
then it became ok!

**Comment by leetal** [comment]
I have now begun adding a test-patch to see if i break anything by caching some variables. Please see #192 if you want to test locally as well :)

**Comment by leetal** [comment]
Fixed in #192
