### ISSUE TITLE
ios with arm neon

### ISSUE THREAD

**Issue by cvv-student** [leetal/ios-cmake#199]
Thanks for your contribution. I have tried writing some NEON instructions in ios, and the compilation was successful. Now I want to port it to CXX for compilation. On Android, there is a specific instruction -DANDROID_ARM_NEON. What should I do on iOS?

**Comment by leetal** [comment]
The C++ ABI should support NEON out-of-the-box already, thus CLANG should have all definitions readiliy available. The header should as always be just `arm_neon.h`.

Closing since this topic is out of scope of this toolchain.
