### ISSUE TITLE
Set CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD based on selected CMAKE_CXX_STANDARD

### ISSUE THREAD

**Issue by EduMenges** [leetal/ios-cmake#204]
[This is an issue that has been opened for 4+ years on CMake](https://gitlab.kitware.com/cmake/cmake/-/issues/19713).

Adding it to the toolchain is a workaround until CMake finally "fixes" it.

In most cases, simply adding `set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++${CMAKE_CXX_STANDARD}")` works, tho it will not work with GNU extensions.

The same can be done for `C_STANDARD`.

**Comment by kambala-decapitator** [comment]
> tho it will not work with GNU extensions

you should use `gnu++${CMAKE_CXX_STANDARD}`

**Comment by leetal** [comment]
Closing this issue as it only contains valuable information for future reference and does not pertain to an active issue with my CMake toolchain itself.
