### ISSUE TITLE
[bug] Why -DPLATFORM=OS64COMBINED only arm64? 

### ISSUE THREAD

**Issue by cc673459362** [leetal/ios-cmake#217]
**Describe the bug**

**To Reproduce**
1. use cmake command
 cmake ../../.. -B build -G Xcode -DCMAKE_TOOLCHAIN_FILE=tools/ios/ios.toolchain.cmake -DPLATFORM=OS64COMBINED -D_BUILD_CLIENT_DEMO=1
or 
add -DARCHS="arm64;x86_64"

2. lipo -info  xxx
Non-fat file:xxx is architecture: arm64

**Expected behavior**
Is it should be arm64 and x86_64?

My MacOS is 14.4.1 and Apple M1  and  XCode 15.4
cmake version 3.29.6

**Comment by leetal** [comment]
As stated here: https://github.com/leetal/ios-cmake?tab=readme-ov-file#combined-options
You need to also run the cmake install to actually run the actual lipo steps internally in cmake.
