### ISSUE TITLE
Does not support ability to build both i386 and x86_64 builds for simulator.

### ISSUE THREAD

**Issue by mobileben** [leetal/ios-cmake#22]
This is related to 

https://github.com/Microsoft/cpprestsdk/issues/1015

Xcode uses armv7 as the trigger point to building i386 slices when building for the simulator. The way to cause this is to build a target that builds for all architectures.

In the case of cpprestsdk, this causes a linker error because there is no i386 slice. cpprestsdk uses this repo.

**Comment by mobileben** [comment]
I can work around this by modifying the CMakeLists.txt file in cpprestsdk. I'm closing this and will re-open if for some reason it looks like there is an issue. I've already built and am just testing some simulator builds.

**Comment by leetal** [comment]
Alright! I'll follow the cpprestsdk issue for further details. 
The thing is that x86 simulator builds is more or less deprecated since Apple do not produce any x86-based Macs anymore and will likely drop that option from Xcode in the coming versions as well.

**Comment by mobileben** [comment]
Yeah, it's deprecated. But Xcode is "internally wired" to use i386 for 32-bit targets. It will be interesting to see what happens if they stop the Intel train on the Macs but still support iOS versions for 32-bit devices.
