### ISSUE TITLE
Use CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE for setup bitcode options [XCode]

### ISSUE THREAD

**Issue by irov** [leetal/ios-cmake#23]
for Enable bitcode use this
set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE "YES" CACHE STRING "Bitcode" FORCE)
for Disable bitcode use this
set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE "NO" CACHE STRING "Bitcode" FORCE)

Thanks!

**Comment by leetal** [comment]
There is a macro in the toolchain that lets you set Xcode specific settings in your own CMakeList-
file. It is called `set_xcode_property`. 

Example usage: `set_xcode_property (example ENABLE_BITCODE YES "All")`

Please look in the example on how to use it (or read the documentation in the toolchain).
