### ISSUE TITLE
Invalid iOS deployment version

### ISSUE THREAD

**Issue by LukasBanana** [leetal/ios-cmake#25]
Hi, I tried to get your iOS CMake Toolchain running but I always get the same error:

```
clang: error: invalid iOS deployment version '-mios-simulator-version-min=12.1',
iOS 10 is the maximum deployment target for 32-bit targets
[-Winvalid-ios-deployment-target]
```

I know 32-bit targets are no longer supported, but I don't understand why the CMake build always sets this target (i.e. i386). No matter if I set `IOS_PLATFORM` macro to `OS` or `SIMULATOR64`.

I also tried different deployment targets: 8.0, 10.0, 12.0, and 12.1.
But since SDK 12.1 is my only installed SDK, the CMake build can only use this one.

Can anyone tell me what I'm doing wrong?

**Comment by leetal** [comment]
Hmmm.... I'll look into this issue right away. It seems like the deployment parameter is somehow set alongside the min deployment version.

**Comment by leetal** [comment]
What build system do you use? xcodebuild, make, ninja, ... ? I cannot reproduce it with my local setup it seems?

**Comment by leetal** [comment]
If using the latest toolchain version released, specifying for example `cmake .. -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DIOS_PLATFORM=SIMULATOR` will work since it will set a deployment target below 10.0 (8.0 currently by default). When building it will always use the latest SDK available in your sysroot.

But if you would run cmake with the following `cmake .. -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DIOS_PLATFORM=SIMULATOR -DIOS_DEPLOYMENT_TARGET="11.0"` it would yield the error you posted above. And this is perfectly OK, since if you specify the `IOS_DEPLOYMENT_TARGET` parameter, you only set what MIN-version you want, not the maximum version. That is determined by the SDK version since the toolchain will always build with the latest and greatest SDK available.

**Comment by LukasBanana** [comment]
I'm using the CMake GUI with the `Xcode` generator. This is the output of the first configuration:
```
Building with Xcode version: 10.1
Configuring iOS build for platform: OS, architecture(s): armv7;armv7s;arm64;arm64e
Using manually set SDK path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk for platform: OS
Using the default min-version since IOS_DEPLOYMENT_TARGET not provided!
Enabling bitcode support by default. ENABLE_BITCODE not provided!
Enabling ARC support by default. ENABLE_ARC not provided!
Hiding symbols visibility by default. ENABLE_VISIBILITY not provided!
Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
Using a data_ptr size of 4
Building for minimum iOS version: 8.0 (SDK version: 12.1)
Version flags set to: -miphoneos-version-min=8.0
Enabling bitcode support.
Enabling ARC support.
Hiding symbols (-fvisibility=hidden).
Building with Xcode version: 10.1
Configuring iOS build for platform: OS, architecture(s): armv7;armv7s;arm64;arm64e
Using manually set SDK path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk for platform: OS
Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
Using a data_ptr size of 4
Building for minimum iOS version: 8.0 (SDK version: 12.1)
Version flags set to: -miphoneos-version-min=8.0
Enabling bitcode support.
Enabling ARC support.
Hiding symbols (-fvisibility=hidden).
The C compiler identification is AppleClang 10.0.0.10001145
The CXX compiler identification is AppleClang 10.0.0.10001145
Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Configuring done
```

I want to build for the latest SDK version (iOS SDK 12.1), but I don't get the i386 setting out of the configuration.

When I use your first command line (i.e. `cmake .. -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DIOS_PLATFORM=SIMULATOR`), the first output I see is this:
```
-- Configuring iOS build for platform: SIMULATOR, architecture(s): i386
```
Which is again the wrong architecture.

**Comment by leetal** [comment]
What if you use SIMULATOR64 instead of SIMULATOR? That target only builds for x86_64.

**Comment by LukasBanana** [comment]
With `SIMULATOR64` in the command line, I get the `x86_64` architecture. The same with the CMake GUI when I change `IOS_PLATFORM` to this value and the output is as follows:
```
Building with Xcode version: 10.1
Configuring iOS build for platform: SIMULATOR64, architecture(s): x86_64
Using manually set SDK path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk for platform: SIMULATOR64
Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
Using a data_ptr size of 8
Building for minimum iOS version: 8.0 (SDK version: 12.1)
Version flags set to: -mios-simulator-version-min=8.0
Enabling bitcode support.
Enabling ARC support.
Hiding symbols (-fvisibility=hidden).
Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   iOSCMakeTest1

This warning is for project developers.  Use -Wno-dev to suppress it.

Generating done
```

Looks good in the CMake log, but I still get the same **linker error** in Xcode (with the i386):
```
Ld /Users/lh/Entwicklung/Tests/Obj-C/iOSAppTest1/build_xcode/iOSCMakeTest1.build/Debug-iphonesimulator/iOSCMakeTest1.build/Objects-normal/i386/libiOSCMakeTest1.dylib normal i386 (in target: iOSCMakeTest1)
    cd /Users/lh/Entwicklung/Tests/Obj-C/iOSAppTest1
    export IPHONEOS_DEPLOYMENT_TARGET=12.1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch i386 -dynamiclib -isysroot 

...

clang: error: invalid iOS deployment version '-mios-simulator-version-min=12.1', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]
```
I'm building a shared library using `ADD_LIBRARY(... SHARED ...)` by the way. I remember from older days (when I was using Xcode 4) that this was not an issue.

**Comment by Diarrhio** [comment]
I'm getting this same issue. I worked around it by only building `OS64` and `SIMULATOR64` platforms as we don't need 32 bit builds anymore, but it seems like a shortcoming in the toolchain file.

I tried patching the toolchain file by also adding the version-min flag to `CMAKE_SHARED_LINKER_FLAGS` and `CMAKE_EXE_LINKER_FLAGS` (since this error only occurs when building shared libs and exes), but w/o any luck. Got stuck and just moved on by omitting `OS` and `SIMULATOR` platforms

**Comment by jonmcclung** [comment]
@Diarrhio thanks, your fix worked for me.

**Comment by leetal** [comment]
I will fix this today so that if targeting versions above 10.0 on iPhones it will remove the 32-bit all together.

**Comment by Diarrhio** [comment]
> I will fix this today so that if targeting versions above 10.0 on iPhones it will remove the 32-bit all together.

Awesome. Thanks!
