### ISSUE TITLE
-fvisibility=hidden causes build error

### ISSUE THREAD

**Issue by sparkkk** [leetal/ios-cmake#3]
I had a very simple CMakeLists.txt:

`cmake_minimum_required (VERSION 3.9)
  
project (testcm)

include_directories(
    "${PROJECT_BINARY_DIR}"
    include)

add_library(func
    SHARED
    func/func.cpp)

add_executable(testcm main/main.cpp)

target_link_libraries(testcm func)`

And after _cmake -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DIOS_PLATFORM=OS .. & make_, I got this
`Undefined symbols for architecture armv7:
  "_func1", referenced from:
      _main in main.cpp.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`
And after removing -fvisibility=hidden from CXXFLAGS set in ios.toolchain.cmake, it works.

**Comment by leetal** [comment]
My first observation is that you are building a  shared library. Hiding symbols in a shared library can cause some symbols to be defined and some not, explicitly needing to be redefined when loading the library during runtime.

What is the result if you try to build a static library instead?

**Comment by sparkkk** [comment]
It works fine when I tried to build and link a static library.

**Comment by sparkkk** [comment]
It works find when I tried to build and link a static library.

> My first observation is that you are building a  shared library. Hiding symbols in a shared library can cause some symbols to be defined and some not, explicitly needing to be redefined when loading the library during runtime.
>
> What is the result if you try to build a static library instead?

**Comment by Kyatak** [comment]
We experienced the same issue when trying to link two dynamic libraries (AWS Kinesis was linking AWS Core). 
So we had to remove the flags to make it work.
How about to make this flag modifiable ? Is it common practice to enable this flag by default?

**Comment by leetal** [comment]
I'll investigate this a little further and then come back with a resolution. There is a few upcoming additions to the toolchain to further improve compatibility with lots of third-party libraries out there. I'll probably make the visibility modifiable as well and also look into shared linking a little deeper with the toolchain. I'm mostly using it to build static libraries tbh. :)

**Comment by leetal** [comment]
A proposed solution is now available at PR #4 . This also address an issue with the simulator missing bitcode support. So from now on, all libs will be built with bitcode on actual device-distributions only.
