### ISSUE TITLE
CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE should be YES instead of ON

### ISSUE THREAD

**Issue by AudioScientist** [leetal/ios-cmake#32]
Hi,

Thanks for your project, so usefull :)

I encountered a minor issue with your latest update, my versions are
- Xcode 10.1,
- cmake 3.14.0.

Here is the issue :

Setting [`CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE` to `ON`](https://github.com/leetal/ios-cmake/blob/4a70452049ed04cf363082dc2faaa0f3f13e8267/ios.toolchain.cmake#L388) doesn't seems to work, it should be set to `YES` instead.  
Same for [`OFF`](https://github.com/leetal/ios-cmake/blob/4a70452049ed04cf363082dc2faaa0f3f13e8267/ios.toolchain.cmake#L393), it should be set to `NO`.

**Comment by leetal** [comment]
I'm actually working on the toolchain right now, so i'll look into this soon :)

**Comment by AudioScientist** [comment]
👌 

Also, the pending pull request turning the `string` into `STRING` would prevent a lots of unwanted warnings 😉

**Comment by leetal** [comment]
Fixed in [v3.0.0](https://github.com/leetal/ios-cmake/tree/3.0.0) 🚀
