### ISSUE TITLE
Overwriting CMAKE_OSX_SYSROOT with an invalid value

### ISSUE THREAD

**Issue by NikitaFeodonit** [leetal/ios-cmake#38]
Here [in the commit](https://github.com/leetal/ios-cmake/commit/db6ed8328999d9a68bac133946560e873445048f#diff-3beef4b19f65ed0d2f7c9c0918502489R287) CMAKE_OSX_SYSROOT becomes like
```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk
```
All is OK.

But here [in the commit](https://github.com/leetal/ios-cmake/commit/db6ed8328999d9a68bac133946560e873445048f#diff-3beef4b19f65ed0d2f7c9c0918502489R292) CMAKE_OSX_SYSROOT becomes like
```
iphonesimulator
```
For what purpose?

And further work is done with CMAKE_OSX_SYSROOT as a path to a file, rather than as the name of the SDK.

**Comment by NikitaFeodonit** [comment]
> And further work is done with CMAKE_OSX_SYSROOT as a path to a file, rather than as the name of the SDK.

In these points:

https://github.com/leetal/ios-cmake/blob/3e5697cd87ca7882783ad3a22c86369256f69f6d/ios.toolchain.cmake#L595

https://github.com/leetal/ios-cmake/blob/3e5697cd87ca7882783ad3a22c86369256f69f6d/ios.toolchain.cmake#L601

**Comment by NikitaFeodonit** [comment]
> For what purpose?

After reading [the documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_SYSROOT.html) it became clearer:

"Specify the location or **name** of the macOS platform SDK to be used."

**Comment by leetal** [comment]
I'll take a look on this today and see what I can come up with. There are some problems with cmake versions above 3.14 that includes the combined builds support that forced me to rewrite the sysroot path.

**Comment by leetal** [comment]
Is this still an issue fo you? The reasoning being that lots have changed since May and i have made some patches in the last months that might have improved the issue with regards to newer versions of CMake being released.

**Comment by NikitaFeodonit** [comment]
Sorry for the long delay in answering. Hopefully I can check this out soon in my project.

**Comment by NikitaFeodonit** [comment]
Nevertheless, I express my gratitude to you for the work done. Sorry I didn't do it right away.

My problem, both earlier and now, is to get exactly the path to the SDK. In my project, I build the Boost library through its build system (```b2```) and the CMake. CMake should pass the compiler path and flags to the ```b2```. For this reason, a name of the SDK cannot be used.

As a result, both earlier and now, I use ```CMAKE_OSX_SYSROOT_INT``` from your ```ios.toolchain.cmake```.

You can see more details in the project repositories.
Explanation and common scripts:
https://github.com/LibCMaker/LibCMaker
Project repository for the Boost building and ```CMAKE_OSX_SYSROOT_INT``` variable usage:
https://github.com/LibCMaker/LibCMaker_Boost/blob/master/cmake/cmr_boost_set_cmake_flags.cmake#L172
```set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isysroot ${CMAKE_OSX_SYSROOT_INT}")```

But ```CMAKE_OSX_SYSROOT_INT``` is a variable for internal use, not documented.

That is, there is a problem with the ```CMAKE_OSX_SYSROOT``` variable, but I am using a workaround with undocumented variable ```CMAKE_OSX_SYSROOT_INT```.

I think the problem can be closed by adding documentation for the ```CMAKE_OSX_SYSROOT_INT``` variable. And at your discretion, you can change the name of the variable.

**Comment by leetal** [comment]
This is now "fixed" on dev where the "CMAKE_OSX_SYSROOT" always points to a path in the requested SDK. It is just setting the value more or less based off "CMAKE_OSX_SYSROOT_INT".
