### ISSUE TITLE
find_package(Boost) no longer works since PR #33

### ISSUE THREAD

**Issue by forderud** [leetal/ios-cmake#39]
I'm experiencing problems with `find_package(Boost)` in recent versions of ios-cmake. It seems like db6ed8328999d9a68bac133946560e873445048f  in PR #33 introduced a regression in this area.

CMake error:
```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindBoost.cmake:2132 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
```

Minimal reproducer: https://github.com/forderud/BoostCMakeIOS

**Comment by leetal** [comment]
Can you try find_host_package(Boost) instead?

**Comment by forderud** [comment]
Thanks a lot for the tip @leetal. `find_host_package(Boost)` did the trick for me. 👍 

One question though: Do you see `find_host_package` as a recommended approach when targeting iOS, or more as a temporary work-around?

**Comment by forderud** [comment]
I've now tested a bit more, and am also experiencing the same `find_package` regression with CMake "packages" built specifically for iOS, like e.g. Qt 5.13.0-beta3, and some of the libraries I'm building myself. In these cases, `find_host_package` should not be needed, right?

**Comment by leetal** [comment]
No it shouldn't. In light of this issue, Kitware is aware of this issue (not this toolchain's fault). It has to do with the new way CMake handles combined builds which I have added support for a couple versions back.

**Comment by forderud** [comment]
Thanks for the explanation @leetal . Then I guess this issue can be closed, since the root cause is in CMake.
