### ISSUE TITLE
find_host_package CMAKE_FIND_ROOT_PATH_MODE_PACKAGE?

### ISSUE THREAD

**Issue by forderud** [leetal/ios-cmake#42]
I see that the `find_host_package` macro sets `CMAKE_FIND_ROOT_PATH_MODE_PROGRAM`, `CMAKE_FIND_ROOT_PATH_MODE_LIBRARY` & `CMAKE_FIND_ROOT_PATH_MODE_INCLUDE` to `NEVER` before forwarding the call to `find_package`. This all looks reasonable, but there's also a similar `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE` variable that is not touched.

Any specific reason for `find_host_package` not doing the same also for `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE`?

**Comment by leetal** [comment]
Actually, i have totally missed that variable 🙃. And since no error have occurred that i can remember due to that variable, i have never even considered adding it. I will test-add it and see if any unexpected stuff happens. If not, I'll consider adding it for brevity.
