### ISSUE TITLE
CMake wrongly sets -mmacosx-version-min if CMAKE_OSX_DEPLOYMENT is set

### ISSUE THREAD

**Issue by JonasVautherin** [leetal/ios-cmake#43]
Is it theoretically possible to build with "Unix Makefiles" instead of "Xcode"? I have been trying to build curl this way, and I get an error because `SIZEOF_LONG` is not defined. Could it be related to the toolchain?

**Comment by JonasVautherin** [comment]
Not that on simple projects, I also get errors like:

```
clang: error: invalid argument '-mmacosx-version-min=9.0' not allowed with '-miphoneos-version-min=9.0'
```

And I am not sure who sets the `macosx` one :thinking:

**Comment by leetal** [comment]
Do you have any reproducer perhaps? It is easier for me to investigate if i have a concrete example. :) The macos version min seems to be populated form elsewhere.. I have been using this toolchain only with makefiles and ninja+llvm so it should work as long as nothing else is fiddling with the CMake params.

**Comment by JonasVautherin** [comment]
So it seems like it is actually [set by CMake](https://cmake.org/cmake/help/v3.0/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html). I had to add the following line to your toolchain (that I copied from another toolchain actually):

    set(CMAKE_OSX_DEPLOYMENT_TARGET "" CACHE STRING "Force unset of the deployment target for iOS" FORCE)

Does it make sense to you, or is it just a "hack" for my case? I can try to come with a reproducible example if you need it.

**Comment by JonasVautherin** [comment]
So I updated CMake to version 3.14.4 from 3.10, and it seems like this go resolved. Sorry for the inconvenience, it seems like CMake was doing it wrong.
