### ISSUE TITLE
Unexpected behavior of CMAKE_FIND_ROOT_PATH_MODE_*

### ISSUE THREAD

**Issue by JonasVautherin** [leetal/ios-cmake#45]
First, I believe the [comment](https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake#L619) is wrong:

> Only search the specified iOS SDK, not the remainder of the host filesystem.

That would be for `ONLY`, but here `BOTH` is [set by default](https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake#L620-L631):

```cmake
if(NOT CMAKE_FIND_ROOT_PATH_MODE_PROGRAM)
  set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH CACHE STRING "" ${FORCE_CACHE})
endif()
if(NOT CMAKE_FIND_ROOT_PATH_MODE_LIBRARY)
  set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH CACHE STRING "" ${FORCE_CACHE})
endif()
if(NOT CMAKE_FIND_ROOT_PATH_MODE_INCLUDE)
  set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH CACHE STRING "" ${FORCE_CACHE})
endif()
if(NOT CMAKE_FIND_ROOT_PATH_MODE_PACKAGE)
  set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH CACHE STRING "" ${FORCE_CACHE})
endif()
```

Then, I somehow don't get the appropriate defaults. Say I create the following example:

```cmake
cmake_minimum_required(VERSION 3.1)
project(CMakeFindRootPathModeExample)

message("CMAKE_FIND_ROOT_PATH_MODE_PACKAGE: ${CMAKE_FIND_ROOT_PATH_MODE_PACKAGE}")
message("CMAKE_FIND_ROOT_PATH_MODE_PROGRAM: ${CMAKE_FIND_ROOT_PATH_MODE_PROGRAM}")
message("CMAKE_FIND_ROOT_PATH_MODE_INCLUDE: ${CMAKE_FIND_ROOT_PATH_MODE_INCLUDE}")
message("CMAKE_FIND_ROOT_PATH_MODE_LIBRARY: ${CMAKE_FIND_ROOT_PATH_MODE_LIBRARY}")
```

And I run it with:

```sh
cmake -DCMAKE_TOOLCHAIN_FILE=/path/to/ios.toolchain.cmake ..
```

I get the following output:

```
CMAKE_FIND_ROOT_PATH_MODE_PACKAGE: BOTH
CMAKE_FIND_ROOT_PATH_MODE_PROGRAM: BOTH
CMAKE_FIND_ROOT_PATH_MODE_INCLUDE: ONLY
CMAKE_FIND_ROOT_PATH_MODE_LIBRARY: ONLY
```

Even if I remove the `if` statements in the toolchain to always set all four to `BOTH`, it ends up like so.

Am I doing something wrong?

**Comment by JonasVautherin** [comment]
I tested the same setup with cmake 3.13.3 (from pip), and there it works. So it seems like a bug in cmake 3.14.4.

@leetal: which version of cmake do you use?

**Comment by JonasVautherin** [comment]
Closing in favor of https://gitlab.kitware.com/cmake/cmake/issues/19282.

**Comment by leetal** [comment]
I have the exact same behavior (issue) and have submitted a previous bug report to Kitware about this. But your linked bug request seems more thorough and well explained! Definitely a bug in CMake that is hopefully fixed with their nightly builds (shall try this tonight) .
