### ISSUE TITLE
CMAKE_TRY_COMPILE_TARGET_TYPE has an open bug in CMake

### ISSUE THREAD

**Issue by JonasVautherin** [leetal/ios-cmake#47]
As reported [here](https://gitlab.kitware.com/cmake/cmake/issues/18121):

> Setting CMAKE_TRY_COMPILE_TARGET_TYPE to STATIC_LIBRARY will subvert the behaviour of the CHECK_FUNCTION_EXISTS macro, causing it to always return true/success (as it will never attempt the link step that is intended to confirm the function availability).

The consequence of that is that some cmake code like:

```cmake
include(CheckLibraryExists)

check_library_exists("some_nonexisting_foo_lib" foo_symbol "${CMAKE_LIBRARY_PATH}" HAVE_FOO)
```

will always set `HAVE_FOO` to True. In my case, it is an issue with Curl, which tests for idn2 and compiles accordingly.

Is there a reason for setting `CMAKE_TRY_COMPILE_TARGET_TYPE` to `STATIC_LIBRARY` in your toolchain? The comment reads: "Change the type of target generated for try_compile() so it'll work when cross-compiling". In my case, removing this line just works to build my project.

Maybe this flag is needed generally, and I should just remove it in my project until the bug is fixed on CMake side, but I wanted to keep a record of that and know if it is really necessary.

**Comment by JonasVautherin** [comment]
So it seems like Xcode needs this flag, but building from clang directly doesn't need it. So probably it would be nice to have a check for the generator and enable `STATIC_LIBRARY` only if the generator is `Xcode`.

**Comment by leetal** [comment]
I have verified that this indeed seems to be the case for quite a few versions back of CMake. I have now made the `try_compile` directive mandatory for Xcode generator only.

**Comment by leetal** [comment]
On a second thought, i will make it opt-out since using cross-compilation toolchains (like this one) more or less always need it set to `STATIC_LIBRARY`. I'll add a variable to opt out (force linker to run) when the CHECK* directives are run.

**Comment by JonasVautherin** [comment]
> i will make it opt-out since using cross-compilation toolchains (like this one) more or less always need it set to STATIC_LIBRARY.

Can you elaborate on that? Cross-compiling with your toolchain, I observe that `Xcode` needs it, but `Unix Makefiles` doesn't. So is it known that cross-compiling "more or less always needs `STATIC_LIBRARY`"? Or is it special for Xcode?

In the end I would also be fine with a cmake option, but it seems to me that the default could auto-detect the generator.
