### ISSUE TITLE
Recent addition of CMAKE_SYSTEM_PROCESSOR breaks some build

### ISSUE THREAD

**Issue by JonasVautherin** [leetal/ios-cmake#48]
It seems to me that [the recent addition](https://github.com/leetal/ios-cmake/commit/29ff9d2f15e9844b9e8fedc89f56bf102d836caa) (solving #40) of `CMAKE_SYSTEM_PROCESSOR` breaks some build.

I am not sure why, so here is a reproducible example:

1. Use the latest `ios.toolchain.cmake` file
2. Use the following CMakeLists.txt, which will basically download and build libressl
3. Run `cmake -DCMAKE_TOOLCHAIN_FILE=/path/to/ios.toolchain.cmake ..`

#### CMakeLists.txt

```cmake
cmake_minimum_required(VERSION 3.1)
  
project(external-libressl)
include(ExternalProject)

set(LIBRESSL_VERSION 2.9.0)

list(APPEND CMAKE_ARGS
    "-DCMAKE_TOOLCHAIN_FILE:PATH=${CMAKE_TOOLCHAIN_FILE}"
    "-DBUILD_SHARED_LIBS=OFF"
    "-DLIBRESSL_APPS=OFF"
    "-DLIBRESSL_TESTS=OFF"
    )

if(IOS)
    list(APPEND CMAKE_ARGS
        "-DPLATFORM=${PLATFORM}"
        "-DCMAKE_C_FLAGS=-Wno-implicit-function-declaration"
        )
endif()

message(STATUS "Preparing external project \"libressl\" with args:")
foreach(CMAKE_ARG ${CMAKE_ARGS})
    message(STATUS "-- ${CMAKE_ARG}")
endforeach()

ExternalProject_add(
    libressl
    URL https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-${LIBRESSL_VERSION}.tar.gz
    PREFIX libressl
    CMAKE_ARGS "${CMAKE_ARGS}"
    )
```

The error I get:

```
[ 75%] Performing build step for 'libressl'
Scanning dependencies of target crypto
[  0%] Building C object crypto/CMakeFiles/crypto.dir/aes/aes-elf-armv4.S.o
/tmp/demo_libressl/build/libressl/src/libressl/crypto/aes/aes-elf-armv4.S:1:10: fatal error: 'arm_arch.h' file not found
#include "arm_arch.h"
         ^~~~~~~~~~~~
```

Removing this addition of `CMAKE_SYSTEM_PROCESSOR` fixes it, I have no idea why.

**Comment by leetal** [comment]
Have you tried building 2.9.1 (or even 2.9.2) of libressl? The arm_arch.h file is actually missing in 2.9.0, but present in the latest two versions.

**Comment by leetal** [comment]
Versions 2.9.1 and up are now working. The error was that when using "OS" as the platform it would target armv7 or lower archs, thus causing mayhem. I have made some slight modifications to actually match "OS" to the correct CMAKE_SYSTEM_PROCESSOR type (since the regex's would match the wrong condition previously on newer versions of CMake).

**Comment by leetal** [comment]
FWIW: I have actually added libressl as a build-step since it represents a good use-case of the toolchain to verify functionality.

**Comment by JonasVautherin** [comment]
Let me confirm that it works with 2.9.1, I'll test that over the weekend.

**Comment by JonasVautherin** [comment]
Using the `CMakeLists.txt` file above with 2.9.1 and your latest toolchain, it fails for me, with errors like `error: unknown directive .size AES_Td,%object` and similar.

How do you build libressl 2.9.1? Maybe I missed something there.

**Comment by leetal** [comment]
Check here: https://github.com/leetal/ios-cmake/blob/8b4bf9c63c528360e5e46f6478866909972f1bb4/.travis/build.sh#L31

Did you test with the dev-branch? I have not pushed this to master yet since the tests "fails" (one of them should fail by design) currently.

**Comment by JonasVautherin** [comment]
Oh I had not seen the dev branch. Let me try that!

**Comment by JonasVautherin** [comment]
Still not working, both building with the `Unix Makefiles` generator and Xcode... with cmake 3.14. Which version of cmake do you have?
