### ISSUE TITLE
iOS SDK 10.0.0 Should still support 32-bit until 10.3.2

### ISSUE THREAD

**Issue by jbfitbit** [leetal/ios-cmake#51]
iOS removed 32-bit support with 10.3.2, but this script will not build 32-bit if using SDK => 10.0 and <= 10.3.2

https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake#L207

https://appleinsider.com/articles/17/03/28/apple-seemingly-ends-support-for-32-bit-devices-with-ios-1032

**Comment by leetal** [comment]
Thanks for finding this! Fixed in #dba3fbc
