### ISSUE TITLE
iphoneos is not an iOS SDK

### ISSUE THREAD

**Issue by syq7970** [leetal/ios-cmake#52]
Building example-lib get an error:

```shell
CMake Error at /usr/local/Cellar/cmake/3.14.5/share/cmake/Modules/Platform/iOS-Initialize.cmake:4 (message):
  iphoneos is not an iOS SDK
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.5/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:2 (project)
```
use cmake 3.15.rc not working.
can some one help me?

**Comment by syq7970** [comment]
Resolved!
`sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer`

**Comment by keyurdoshi18** [comment]
Thanks a lot!!

**Comment by Vishnu0306** [comment]
Hi Team,

Even though i have been facing same issue

CMake Error at /usr/local/Cellar/cmake/3.23.2/share/cmake/Modules/Platform/iOS-Initialize.cmake:4 (message):
   is not an iOS SDK
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.23.2/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:3 (project)

**Comment by PlinChen** [comment]
> https://github.com/leetal/ios-cmake/issues/52#issuecomment-1220275237
I met this too. It seems `_CMAKE_OSX_SYSROOT_PATH` was set to "" somewhere, but I couldn't find the exact place.

**Comment by PlinChen** [comment]
> Hi Team,
> 
> Even though i have been facing same issue
> 
> CMake Error at /usr/local/Cellar/cmake/3.23.2/share/cmake/Modules/Platform/iOS-Initialize.cmake:4 (message): is not an iOS SDK Call Stack (most recent call first): /usr/local/Cellar/cmake/3.23.2/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include) CMakeLists.txt:3 (project)
> 
> cmake version 3.23.2

I got it. Upgrading cmake to the latest version works for me.
1. upgrade via `brew install cmake` or `brew reinstall cmake`
1. remove `build` directory manually and rebuild again, it would work.

**Comment by Vishnu0306** [comment]
Thank you so much @PlinChen 

It is resolved.
