### ISSUE TITLE
Cannot specify a custom toolchain

### ISSUE THREAD

**Issue by wzp301** [leetal/ios-cmake#54]
Hello!

I installed a custom LLVM6.0.1.xctoolchain to the /Library/Developer/Toolchains directory. In order to modify the xocde default toolchain in cmake, I added the following options to the cmake file.

```
set(CMAKE_C_COMPILER /Library/Developer/Toolchains/LLVM6.0.1.xctoolchain/usr/bin/clang)
set(CMAKE_CXX_COMPILER /Library/Developer/Toolchains/LLVM6.0.1.xctoolchain/usr/bin/clang++)
```

But the xcode project generated by cmake still uses the default compiler.

Cmake output log：

```
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
```

How to replace XcodeDefault.xctoolchain with LLVM6.0.1.xctoolchain with cmake command? Look forward to your favourable reply.

**Comment by leetal** [comment]
This is now fixed on dev! Release is planned for version 4.2.
