### ISSUE TITLE
Code Signing Error: No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "123456789A" with a private key was found.

### ISSUE THREAD

**Issue by jonmcclung** [leetal/ios-cmake#56]
I was using an earlier version of this toolchain which was working well. I recently switched to HEAD and now I'm getting the following error:

> Code Signing Error: No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "123456789A" with a private key was found.

After lots of fruitless Googling I tried to open the project in Xcode and build it from there instead of using `cmake --build` from the command line. I then noticed that the Development Team (under Build Settings) was "123456789A" instead of the correct value: "Jon McClung (Personal Team)". Manually changing that allowed the build to continue. This made me wonder where "123456789A" was coming from, so I did a global search and found the CMake variable [`CMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM`](https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake#L333). After changing the Development Team back to "123456789A" in Xcode and setting this variable, the error was resolved. 

I'm opening this issue so that other developers who run into the same problem can know how to fix it.

**Comment by CaiJingLong** [comment]
Maybe my understanding is not very good.

I now set the environment variable in the CMakeLists.txt with the set command.
`set(CMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM cjl_spy@163.com CACHE INTERNAL "")`. And I get error:

```bash
Code Signing Error: No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "cjl_spy@163.com" with a private key was found.
```

Can I do the packaging without signing, my goal is to build a library without using a graphical interface.
For example: Use the CI program to complete the compilation of the source code to the framework.

Do you have any workable suggestions? @jonmcclung

**Comment by jonmcclung** [comment]
@CaiJingLong I believe the workflow to find the correct id is 

1. Launch Keychain Access
2. Open the Apple Development certificate
3. Right Click > Get Info
4. Find the key for Development Team

Unfortunately cannot verify at this time. Hope it helps.

**Comment by vHanda** [comment]
For anyone here looking for a solution -

* I found my team id by following - https://stackoverflow.com/questions/49935433/no-signing-certificate-ios-development-found-protractor-ipad-real-device
* I replaced the team-id line `set(CMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM 123456789A CACHE INTERNAL "")` in ios-cmake with my team id
