### ISSUE TITLE
Symbols not hidden

### ISSUE THREAD

**Issue by nttri** [leetal/ios-cmake#65]
Hi guys,
I'm following the `example usage` to build the example. Then I run the app with Xcode + Simulator to build the app. Then I open the app execute file with Hopper Disassembler (a tool can decompiler) and I still see the function name in the example-lib (`helloworld()`) and how it run inside. So is this a bug in this project or did I need to config anything else to make symbols hidden?
Thank you!

**Comment by mologie** [comment]
You misunderstood what -fvisibility=hidden does. It does not "hide" your symbols from someone who reverse engineers your application, it just hides them from the user. Let's start with a `test.c` program:

```c
#include <stdio.h>
void foo() { printf("hello"); }
int main() { foo(); }
```

And run the following commands on it:

```
# hiccup @ reginn in /tmp [2:10:07] C:130
$ clang test.c -o test_default

# hiccup @ reginn in /tmp [2:10:12] 
$ clang -fvisibility=hidden -fvisibility-inlines-hidden test.c -o test_hidden

# hiccup @ reginn in /tmp [2:10:32] 
$ nm test_default 
0000000100008008 d __dyld_private
0000000100000000 T __mh_execute_header
0000000100003f48 T _foo
0000000100003f64 T _main
                 U _printf
                 U dyld_stub_binder

# hiccup @ reginn in /tmp [2:10:37] 
$ nm test_hidden 
0000000100008008 d __dyld_private
0000000100000000 T __mh_execute_header
0000000100003f48 t _foo
0000000100003f64 t _main
                 U _printf
                 U dyld_stub_binder
```

As you can see `foo` is still there, but it it becomes a private symbol meaning that the dynamic linker will ignore it (local symbol). This protects against accidentally linking against private functions, that's all.

What you want to do is stripping the binary:

```
# hiccup @ reginn in /tmp [2:10:40] 
$ strip test_hidden 

# hiccup @ reginn in /tmp [2:13:22] 
$ nm test_hidden   
0000000100000000 T __mh_execute_header
                 U _printf
                 U dyld_stub_binder
```

Note: This won't work for Objective-C. There is no way to strip Objective-C symbol names, you need some obfuscator instead.

**Comment by mologie** [comment]
Hah, I just saw that this issue is from 2019 :D Well, I hope my response at least helps @leetal who maintains this.

**Comment by leetal** [comment]
Yes that is completely true! I will close this issue since actual obfuscation never was a target for the toolchain itself. Only mere symbol visibility (which Apple by the way more or less enforces/highly recommends using).
