### ISSUE TITLE
ASM sources not correctly picking up iOS flags

### ISSUE THREAD

**Issue by Naville** [leetal/ios-cmake#67]
As a result ASM objects are still built using native arch (missing ``-arch arm64`` in compile flags)

**Comment by leetal** [comment]
I'll look into this in the coming days. We have not really had any need for ASM  compilation so frankly, this is untested in this toolchain :(

**Comment by leetal** [comment]
I have now pushed some changes to the dev branch. Please test with that and see if that resolves your issues.
