### ISSUE TITLE
Problems with simple C++ sample and your toolkit (FAT/COMBINED)

### ISSUE THREAD

**Issue by prsolucoes** [leetal/ios-cmake#68]
Hi,

First, you make a great toolkit, good job!

Second, im trying use your toolkit to build a simple FAT/COMBINED library and use on xcode.

The problem is that generated library is only with one "arch".

There is a test on my sample repository, and the problem can be checked there:
https://travis-ci.com/prsolucoes/ios-lib-test/builds/138626985#L873

Im calling your toolkit with the params:
https://github.com/prsolucoes/ios-lib-test/blob/master/Makefile#L24

It is strange, because if i run install it generate the library into system folder with all archs inside:
/usr/local/lib/libcpp_lib_test.a

The command to install is here:
https://github.com/prsolucoes/ios-lib-test/blob/master/Makefile#L40

Can you help me understand the problem?

Thanks.

**Comment by ligonzheng** [comment]
I also had this problem. Sad !

**Comment by leetal** [comment]
Looking into this! What version of CMake are you using?

**Comment by prsolucoes** [comment]
cmake version 3.14.2

**Comment by leetal** [comment]
Ok, i have now checked your build commands. The tricky thing with *COMBINED is that it will only combine if running the `install` target by design in CMake. The thing i have been struggling with solving is the fact that as you say, it will always install into /usr/local.. No matter what install locations i provide. I'll look into that.

**Comment by leetal** [comment]
So it seems like the default values have not been touched. Setting the following in you CMakeLists.txt will allow for better paths:
```cmake
if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
  set(CMAKE_INSTALL_PREFIX <path> CACHE PATH "Install path" FORCE)
endif(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
```
This must be set before the install target. If `CMAKE_INSTALL_PREFIX` is specified, it will indeed install into the correct location specified by you.

**Comment by prsolucoes** [comment]
Hi,

Yes, it is working on install and with custom prefix.

It is here:
https://travis-ci.com/prsolucoes/ios-lib-test/builds/140100510

And repository is:
https://github.com/prsolucoes/ios-lib-test

Thanks.
