### ISSUE TITLE
Could NOT find Git (missing: GIT_EXECUTABLE)

### ISSUE THREAD

**Issue by kkutsner** [leetal/ios-cmake#7]
Because the line https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake#L411 sets CMAKE_FIND_ROOT_PATH_MODE_PROGRAM to "ONLY" CMake no longer can locate git executable when it is required. For example if I have CMakeLists.txt that contains:
```
find_package(GIT REQUIRED)
```
CMake will generate error:
```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Git (missing: GIT_EXECUTABLE)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindGit.cmake:83 (find_package_handle_standard_args)
  cmake-modules/Catch2.cmake:9 (find_package)
  CMakeLists.txt:56 (include)
```

My setup is: 
```
cmake version 3.12.0-rc1
git version 2.17.1
Xcode 9.4 Build version 9F1027a
```

**Comment by leetal** [comment]
Hi!

There exists a macro in the toolchain that was created for just this specific issue: `find_host_package`.

Use that instead of `find_package` to solve your issue.
