### ISSUE TITLE
How to generate XCFramework?

### ISSUE THREAD

**Issue by prsolucoes** [leetal/ios-cmake#72]
Hi,

With the xcode version 11 we can generate XCFramework to use with Mac Catalyst.

How to generate XCFramework with cmake and this toolchain?

Thanks.

**Comment by prsolucoes** [comment]
I tested with my project https://ezored.com and to build it you need put all ios archs inside one framework, simulator into another framework and macos into another framework. After create separated frameworks you can call:

```
mkdir -p build/ios_framework/Release/xcf

xcodebuild -create-xcframework \
    -framework build/ios_framework/Release/iOS/Ezored.framework \
    -framework build/ios_framework/Release/iOS-simulator/Ezored.framework \
    -framework build/ios_framework/Release/macOS/Ezored.framework \
    -framework build/ios_framework/Release/tvOS/Ezored.framework \
    -framework build/ios_framework/Release/watchOS/Ezored.framework \
    -output build/ios_framework/Release/xcf/Ezored.xcframework
```

Can you add this into your scripts?

**Comment by leetal** [comment]
Sadly, generating frameworks and after that a xcframework is currently out of scope for this project. But, as you have showed, it is pretty easy once you have your frameworks to combine them into the new xcframework package.
