### ISSUE TITLE
[bug]   fatal error:   /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo:   input file (/usr/local/lib/libconfig.a) must be a fat file when the -remove   option is specified

### ISSUE THREAD

**Issue by manang** [leetal/ios-cmake#76]
**Describe the bug**
I'm trying to compile and install libconfig for ios.
the first compilation+instsallation is ok, but the second time I have this error:
  fatal error:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo:
  input file (/usr/local/lib/libconfig.a) must be a fat file when the -remove
  option is specified
it is the same for all the libraries that I want to recompile

**To Reproduce**
1:download a libconfig
2: cd libconfig && mkdir -p build && cd build
3: cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../../ios-cmake/ios.toolchain.cmake -DPLATFORM=OS64COMBINED  -DCMAKE_INSTALL_PREFIX=../../usr -DBUILD_SHARED_LIBS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF
4: cmake --build . --config Release --target install

**Expected behavior**
the library has to be compiled and installed in the usr folder

**Environment**
mac os x 10.15.3
xcode 11.3.1
* What version of CMake did you run?
3.16.3

error:
[bug]   fatal error:   /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo:   input file (/usr/local/lib/libconfig.a) must be a fat file when the -remove   option is specified

**Comment by russes** [comment]
I'm not convinced this error is caused by iOS.cmake.  

When I've been looking at this bug, I'm looking at CMakeIOSInstallCombined.cmake to figure out what's happening.

**Comment by russes** [comment]
For the past couple of days, I've been trying to fix this error by modifying CMakeIOSInstallCombined.cmake.

You can modify CMakeIOSInstallCombined.cmake to fix the fat-file "-remove" problem.  Once you make the modifications to convert an archive to a fat-file, the build will fail elsewhere when "lipo" is run.

I can give you what I have.  I think the best course of action is to file a bug report with Kitware or RADAR report.  Either bug report would require a simple example case, which could be difficult to create.

**Comment by russes** [comment]
I just tried my build with Xcode 11.4 & CMake 3.17.  This build issue still exists with this combination.  Just trying to save someone else some time dealing with this issue.

**Comment by leetal** [comment]
Just as russes mentions, this is an issue with CMake's core functionality rather than this toolchain. I'll create an issue if none exists about this in their issue tracker.

**Comment by leetal** [comment]
This is fixed upstreams in newer versions of CMake (3.19.5+) and should no longer be an issue. Please re-open this issue if the problems still exists.
