### ISSUE TITLE
Unable to find built library

### ISSUE THREAD

**Issue by MarcoCount** [leetal/ios-cmake#77]
I'm completely new to this field and I hope this isn't a stupid question.
I need to build https://github.com/nlohmann/json for iOS.

I cloned this repo and the json lib repo.
I created a dir in the json lib repo and from there I executed:
`cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=CLONED_REPO/ios.toolchain.cmake -DPLATFORM=OS64COMBINED -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED="NO" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY=""`
`cmake --build . --config Release --target install`

The build appeared to have finished correctly.

I have no idea where to find the the built fat library.
I was only able to find /usr/local/include/json.hpp
I was not able to find any *.a file in the build directory or anything similar.

Thanks in advance for the help.

**Comment by manang** [comment]
Hi Marco,

try adding -DCMAKE_INSTALL_PREFIX=<target folder>

I think that the json project does not build a fat library, but it executes only a list of tests

try to skip the tests:

`cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=CLONED_REPO/ios.toolchain.cmake -DPLATFORM=OS64COMBINED -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED="NO" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY="" -DCMAKE_INSTALL_PREFIX=../../usr -DJSON_BuildTests=OFF
cmake --build . --config Release --target install`

**Comment by manang** [comment]
on the json readme you can read:

> Trivial integration. Our whole code consists of a single header file json.hpp. That's it. No library, no subproject, no dependencies, no complex build system. The class is written in vanilla C++11. All in all, everything should require no adjustment of your compiler flags or project settings.

**Comment by manang** [comment]
The last thing:
you need to put another cmake parameter to tell to cmake where you put your libraries 
-DCMAKE_FIND_ROOT_PATH=<where you install the headers and libs>

for example

`
cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=CLONED_REPO/ios.toolchain.cmake -DPLATFORM=OS64COMBINED -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED="NO" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY="" -DCMAKE_INSTALL_PREFIX=../../usr -DJSON_BuildTests=OFF  -DCMAKE_FIND_ROOT_PATH=../../usr`
` cmake --build . --config Release --target install
`

**Comment by MarcoCount** [comment]
Thanks a lot for your help, it helped me a lot!
