### ISSUE TITLE
[RFE] Expose an autoconf compatible target/host triplet variable

### ISSUE THREAD

**Issue by ceztko** [leetal/ios-cmake#78]
This is suggestion to expose a variable with a correctly formed host/target triplet variable that can be used in autoconf builds. Triplets, in the forms like `aarch64-apple-darwin`, are commonly used to configure host and/or target systems in autoconf generated `./configure` scripts, by using `--host` and `--target` switches. Adding this feature eases the use of the CMake toolchain file to compile other projects using CMake `ExternalProject` facility. Android NDK toolchain file exposes a similar variable called [`ANDROID_HEADER_TRIPLE`](https://github.com/floooh/fips/blob/master/cmake-toolchains/android.toolchain.cmake) (as far as I know there's no canonical name). Tentative CMake variable names could be `APPLE_HOST_TRIPLE`/`APPLE_TARGET_TRIPLE`. Also only the former could be added because usually if no target is explicitly specified it's assumed to be the same as host. I expect the matrix of the possible values to be actually quite small: the vendor should be always `apple`, the operating system should be always `darwin`, the architectures are probably just `arm`, `aarch64`, `x86_64`. Also WatchOS, TvOS targets probably uses same triplets as iPhoneOS. More references on system triplets can be found in [1][2][3].

[1] https://wiki.osdev.org/Target_Triplet
[2] http://llvm.org/doxygen/classllvm_1_1Triple.html
[3] https://github.com/gcc-mirror/gcc/blob/master/config.sub

**Comment by ceztko** [comment]
Sorry, this is not a bug but I don't know how to change the label, assuming I have the permissions to do so.

**Comment by leetal** [comment]
Hi! I'll look into this in the coming days!
