### ISSUE TITLE
[bug] Check dependencies Code Signing Error: Bundle identifier is missing. synthesis doesn't have a bundle identifier. Add a value for PRODUCT_BUNDLE_IDENTIFIER in the build settings editor.

### ISSUE THREAD

**Issue by mandagod** [leetal/ios-cmake#79]
Check dependencies
Code Signing Error: Bundle identifier is missing. synthesis doesn't have a bundle identifier. Add a value for PRODUCT_BUNDLE_IDENTIFIER in the build settings editor.

**Comment by leetal** [comment]
This is an issue with your project. The built project needs a bundle identifier (xxx.yyy.zzz, eg. com.leetal.myawesomeproject). Adding this (with your own values) `set_xcode_property(MyAwesomeTarget PRODUCT_BUNDLE_IDENTIFIER "com.leetal.myawesomeproject" All)` would probably fix your issues.

**Comment by codwam** [comment]
> This is an issue with your project. The built project needs a bundle identifier (xxx.yyy.zzz, eg. com.leetal.myawesomeproject). Adding this (with your own values) `set_xcode_property(MyAwesomeTarget PRODUCT_BUNDLE_IDENTIFIER "com.leetal.myawesomeproject" All)` would probably fix your issues.

I found this problem in xcode 14.3.1?

**Comment by Treata11** [comment]
> This is an issue with your project. The built project needs a bundle identifier (xxx.yyy.zzz, eg. com.leetal.myawesomeproject). Adding this (with your own values) `set_xcode_property(MyAwesomeTarget PRODUCT_BUNDLE_IDENTIFIER "com.leetal.myawesomeproject" All)` would probably fix your issues.

@leetal 
That seems to be deprecated ...
```bash
CMake Error at CMakeLists.txt:45 (set_xcode_property):
  Unknown CMake command "set_xcode_property".
```
I think this has to be managed with `set_property` instead...

**Comment by Treata11** [comment]
> @Treata11 the toolchain does provide such macro:
> 
> https://github.com/leetal/ios-cmake/blob/ad96a372b168930c2a1ff9455e1a9ccb13021617/ios.toolchain.cmake#L1122
> 
> alternatively, better use `set_target_properties`

@kambala-decapitator 

I got the error from a project using this toolchain. Don't have an idea why that happened.
But thanks for clarification.

**Comment by kambala-decapitator** [comment]
> I got the error from a project using this toolchain. Don't have an idea why that happened.

no idea what your issue is. Maybe you forgot to pass `--toolchain` parameter or respective cache variable in cmake configuration step?

Can't reproduce your issue on the example project that's included in the repo (it has a call to `set_xcode_property`):
```
cd example/example-lib
cmake -S . -B build -G Ninja --toolchain ../../ios.toolchain.cmake -D PLATFORM=SIMULATOR64
```

**Comment by Treata11** [comment]
> > I got the error from a project using this toolchain. Don't have an idea why that happened.
> 
> no idea what your issue is. Maybe you forgot to pass `--toolchain` parameter or respective cache variable in cmake configuration step?
> 
> Can't reproduce your issue on the example project that's included in the repo (it has a call to `set_xcode_property`):
> 
> ```
> cd example/example-lib
> cmake -S . -B build -G Ninja --toolchain ../../ios.toolchain.cmake -D PLATFORM=SIMULATOR64
> ```

I checked it again... I had a staled CMake cache. My mistake right from the beginning.

Just to ask something while here.
The official iOS-build support comes with CMake 3.14?

**Comment by kambala-decapitator** [comment]
> The official iOS-build support comes with CMake 3.14?

I think they only simplified some things in 3.14, e.g. introduced `IOS` variable. See release notes here: https://cmake.org/cmake/help/latest/release/3.14.html#platforms

you can build for iOS with < 3.14 as well.
