### ISSUE TITLE
very slow check_c_source_compiles

### ISSUE THREAD

**Issue by manang** [leetal/ios-cmake#80]
**Describe the bug**
Hi, I noticed that when I execute cmake, I need a lot of time to finish the cmake phase.
For example, I'm trying to compile libcurl and it contains a lot of tests, so a lot of check_c_source_compiles.
I need more than 1 hour to finish the cmake phase.
do you have an idea to correct this issue?
Thank you very much
Angelo

**Comment by sk2212** [comment]
Can confirm this issue. Any patch for that?

**Comment by leetal** [comment]
That is weird... The irony in this is that i actually build libcurl on travis for this repo as a test. https://travis-ci.org/github/leetal/ios-cmake/jobs/628312917 
And the complete time for OS64COMBINED is just shy of 35 minutes there...

**Comment by leetal** [comment]
This is now fixed on both master and dev! Released in version 4.1.1

**Comment by leetal** [comment]
It’s important to know that due to the nature of the build system in Xcode, it will always be much slower than other generators. My preferred generator will always be Ninja.
