### ISSUE TITLE
[bug] CMAKE_FIND_ROOT_PATH_MODE_* inconsistency.

### ISSUE THREAD

**Issue by takacsd** [leetal/ios-cmake#81]
**Describe the bug**
The CMAKE_FIND_ROOT_PATH_MODE_* options are set here: https://github.com/leetal/ios-cmake/tree/a0139984e7f397ad85a3f758eff8bd0b09f08cd1/ios.toolchain.cmake#L662-L674
Problems: 
- as per the comment it should be "BOTH" for all
- in the find_host_package macro (https://github.com/leetal/ios-cmake/tree/a0139984e7f397ad85a3f758eff8bd0b09f08cd1/ios.toolchain.cmake#L662-L674) it gets set back to BOTH
- I spent half a day figuring out why my FIND_PATH behaves incorrectly...

**To Reproduce**
1. Use FIND_PATH with path from the host system

**Expected behavior**
I think the default should be BOTH. If not, at least there should be a warning in the readme or in the help.
In any case `find_host_package` should preserve the original settings.

**Environment**
* CMake 3.15

**Comment by leetal** [comment]
Yes! You are very correct. I'll try to work around the settings a little to prevent breaking stuff for people. Ths ting is that on older versions of Xcode, using "BOTH" would actually look up the wrong packages for XCTest and such.
