### ISSUE TITLE
bug or not, bitcode flag not used when building for sim64 using the  XCode generator

### ISSUE THREAD

**Issue by a4z** [leetal/ios-cmake#84]
I am not sure if this is a bug or not, 
I have to build several projects, you can take for example this, https://github.com/eclipse/paho.mqtt.c, 
but the problem applies to all I have in the chain, there is no bitcode in the produces libraries

cmake arguments are 
` -DPLATFORM=SIMULATOR64 -DDEPLOYMENT_TARGET=10.0 -DARCHS=x86_64 -DENABLE_BITCODE=True -DENABLE_ARC=True -DENABLE_VISIBILITY=False -DENABLE_STRICT_TRY_COMPILE=False` 

when changing the cmake generator from Xcode to Ninja, the bitcode flag is applied and the produced libraries have the __LLVM or __bitcode symbol in their brinary.
But not when build via Xcode generator.

I looked through the toolchain file, and it claims that if the Xcode generator is used this will figure out everything.
And it applies the bitcode flags for the arm iOS builds but as it seems not for the simulator build.

Q: is this on purpose ? Does the bitcode flag makes no sense for simulator builds (well I think it does not) 
But I wonder also about consistency, since I build a lot of libs (via conan) those that are build with other toolchains then cmake will contain the bitcode in the simulator binaries, and as long as I do not switch to Ninja as build tool the ones build with cmake will not

**Comment by leetal** [comment]
Hi! I'll look into this during next week. Sorry for not reaching out sooner. Vacation is now over ;)

**Comment by a4z** [comment]
I cross checked with what XCode is doing, and it does not apply bitcode flags to builds for the simulator, or for maccatalyst.

So not having the bitcode section in the simulator build is normal.
