### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by caoguoqing** [leetal/ios-cmake#9]
cmake .. -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DIOS_PLATFORM=SIMULATOR64
CMake Error: The source directory "/Users/mr/Downloads/ios-cmake-master/example" does not appear to contain CMakeLists.txt.        cd build ，cmake build error，what is happen？

**Comment by leetal** [comment]
I'll assume you tried to build the example, but the example in this project resides under example/example-lib, and it looks like you tried to build the example folder which does not contain the required CMakeLists.txt file. I have updated the readme to reflect the path in the example folder.
