### ISSUE TITLE
target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphoneos' platform

### ISSUE THREAD

**Issue by j3g** [leetal/ios-cmake#95]
**Describe the bug**
When I try to build a very basic cmake project, I get the following "Check dependencies" error:
`target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphoneos' platform`

I am getting this error for most of the open source project i'm trying to cross-compile. The example projects build WITHOUT this error. So it is likely I am making a mistake.

**To Reproduce**
1. mkdir build && cd build
2. cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=/Volumes/D1/dev/proj/.../cmake-ios/ios.toolchain.cmake -DPLATFORM=OS64
3. cmake --build . --config Debug

**Expected behavior**
I am trying to compile open source libraries. For example argon2, curl, etc.

**Environment**
* What version of CMake did you run? 3.17.2
* Your faulty CMakeLists.txt here:
```cmake
cmake_minimum_required(VERSION 3.1)
  
project(external-argon2)
include(ExternalProject)

if(IOS)
    list(APPEND CMAKE_ARGS
        "-DPLATFORM=${PLATFORM}"
    )
endif()

ExternalProject_add(
    argon2
    URL https://github.com/yandex/argon2/archive/master.zip
    PREFIX argon2
    CMAKE_ARGS "${CMAKE_ARGS}"
    )

```

**Comment by leetal** [comment]
What that error means is that some target in that external project wants to build a command-line tool (com.apple.product-type.tool) which is not supported on iOS. You must remove that target (most probably by passing -DBUILD_BENCHMARK=OFF and/or -DBUILD_TESTS=OFF) before building the library itself.
