### ISSUE TITLE
Is it possible to build for macosx platform?

### ISSUE THREAD

**Issue by Autokaka** [leetal/ios-cmake#96]
In source code, it seems that ios-cmake only build for ios, tvos and watchos. Is it possible to build for macosx platform?

**Comment by leetal** [comment]
As of now, invoking cmake on a macOS host system without the toolchain file, will build for host. So, it's quite easy to build for host, but cross-compiling and have a catalyst compatible slice is tougher and something i'm looking into myself currently. 

I will close this issue, but i'll consider adding a rather redundant setting for macOS builds as well in the toolchain.
